baseURL = "https://heuristic-wiles-3679a0.netlify.com/"
languageCode = "en-us"
title = "Asian & African Food Shop"
theme = ['alpha-church']

#rssLimit = 5
#enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Paramaters for the whole site
[params]
  title = "Asian & African Food Shop"
  subtitle = "OPEN EVERYDAY"
  author = "Arjun Kamath"

  customCSS = ["css/my.css"]

  [params.map]
    # For Open Street Map widgets
    latitude = "60.15849"
    longitude = "24.74160"
    zoom = "14"

  [params.contact]
    enable = false

  #Paramaters for the home/landing page
  [params.landing]

    [params.landing.banner]
      image = "img/banner.jpg"

    #Details for the box below the banner
    [params.landing.services]
      title = "We are near Iso Omena"
      text = "<b>Ma-La:</b> 10-17:30, <b>Su:</b> 11-17:30."      

    [params.landing.feature_icons]
      #These feature icons look best if there's an even number of them.
      enable = true

      #Accent is a colour defined in the CSS file. Choose between 1 and 5
      [[params.landing.feature_icons.tile]]
        icon = "fa-clock"
        icon_pack = "fas"
        accent = "2"
        title = "Mon- Sat: 11-20 & Sun: 12-20"

      [[params.landing.feature_icons.tile]]
        icon = "fa-map-marked"
        icon_pack = "fas"
        accent = "1"
        title = "Matinkatu 5, 02230, Espoo"
        text = "<b>Ph:</b> +358 50 468 7134"

    [params.landing.feature_images]
      #These feature images look best if there's an even number of them.
      enable = false

      [[params.landing.feature_images.tile]]
        title = "Address: Kala Maija 2, 02230, Espoo"
        text = "<b>Ph:</b> +358 50 468 7134"

      [[params.landing.feature_images.tile]]
        image = "img/snacks.jpg"
        title = "...and Indian savouries"
    
    [params.landing.CTA]
      heading = "We're a small family business!"
      message = "Do come over and say hi!"

    [params.footer]
      copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)",
                   "Developed by [Arjun Kamath](//arjunkamath.com)"
                  ]
        
